USE mysql;
GRANT ALL PRIVILEGES ON *.* TO 'pamadb'@'localhost' IDENTIFIED BY 'qwer4321!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'pamadb'@'%' IDENTIFIED BY 'qwer4321!' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON *.* TO 'pamauser'@'localhost' IDENTIFIED BY 'qwer4321!' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'pamauser'@'%' IDENTIFIED BY 'qwer4321!' WITH GRANT OPTION;
FLUSH PRIVILEGES;